"""add_menu_table

Revision ID: 16b2eeb93189
Revises: b68c772f09d0
Create Date: 2026-01-22 16:48:36.213303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b2eeb93189'
down_revision: Union[str, Sequence[str], None] = 'b68c772f09d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_menus',
    sa.Column('id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='菜单标题'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('path', sa.String(length=100), nullable=True, comment='前端路由路径'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menus_id'), 'sys_menus', ['id'], unique=False)
    op.alter_column('cmdb_resources', 'id',
               existing_type=sa.INTEGER(),
               comment='资源ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cmdb_resources', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='资源名称/实例名',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='资源类型',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment='资源提供商',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'region',
               existing_type=sa.VARCHAR(length=50),
               comment='区域/地域',
               existing_nullable=True)
    op.alter_column('cmdb_resources', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='资源状态',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='资源详细规格数据(JSON)',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='资源标签(JSON)',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cmdb_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_roles', 'id',
               existing_type=sa.INTEGER(),
               comment='角色ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
    op.alter_column('sys_roles', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='角色描述',
               existing_nullable=True)
    op.alter_column('sys_roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='权限集合(JSON格式)',
               existing_nullable=False)
    op.alter_column('sys_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_users', 'id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('sys_users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='邮箱',
               existing_nullable=False)
    op.alter_column('sys_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('sys_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=False)
    op.alter_column('sys_users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='是否为超级管理员',
               existing_nullable=False)
    op.alter_column('sys_users', 'role_id',
               existing_type=sa.INTEGER(),
               comment='角色ID',
               existing_nullable=True)
    op.alter_column('sys_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_users', 'role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=True)
    op.alter_column('sys_users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为超级管理员',
               existing_nullable=False)
    op.alter_column('sys_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('sys_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('sys_users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
    op.alter_column('sys_users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('sys_users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='权限集合(JSON格式)',
               existing_nullable=False)
    op.alter_column('sys_roles', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('sys_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    op.alter_column('sys_roles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cmdb_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cmdb_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cmdb_resources', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='资源标签(JSON)',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='资源详细规格数据(JSON)',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源状态',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'region',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='区域/地域',
               existing_nullable=True)
    op.alter_column('cmdb_resources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源提供商',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源类型',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='资源名称/实例名',
               existing_nullable=False)
    op.alter_column('cmdb_resources', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='资源ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_sys_menus_id'), table_name='sys_menus')
    op.drop_table('sys_menus')
    # ### end Alembic commands ###
