"""add_resource_groups_and_permissions

Revision ID: 2f2785699e8e
Revises: 5b1a92a8026b
Create Date: 2026-03-06 15:14:24.278216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2785699e8e'
down_revision: Union[str, Sequence[str], None] = '5b1a92a8026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmdb_resource_groups',
    sa.Column('id', sa.Integer(), nullable=False, comment='分组ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分组名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分组描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmdb_resource_groups_id'), 'cmdb_resource_groups', ['id'], unique=False)
    op.create_index(op.f('ix_cmdb_resource_groups_name'), 'cmdb_resource_groups', ['name'], unique=True)
    op.create_table('cmdb_resource_group_items',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cmdb_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['cmdb_resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'group_id')
    )
    op.create_table('cmdb_resource_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='资源ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='分组ID'),
    sa.Column('permission', sa.String(length=10), nullable=False, comment='权限类型: read/write'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['cmdb_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['cmdb_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmdb_resource_permissions_id'), 'cmdb_resource_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_cmdb_resource_permissions_user_id'), 'cmdb_resource_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmdb_resource_permissions_user_id'), table_name='cmdb_resource_permissions')
    op.drop_index(op.f('ix_cmdb_resource_permissions_id'), table_name='cmdb_resource_permissions')
    op.drop_table('cmdb_resource_permissions')
    op.drop_table('cmdb_resource_group_items')
    op.drop_index(op.f('ix_cmdb_resource_groups_name'), table_name='cmdb_resource_groups')
    op.drop_index(op.f('ix_cmdb_resource_groups_id'), table_name='cmdb_resource_groups')
    op.drop_table('cmdb_resource_groups')
    # ### end Alembic commands ###
