"""add_cmdb_fields

Revision ID: 56d86dd10df5
Revises: 16b2eeb93189
Create Date: 2026-01-26 09:54:47.662848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d86dd10df5'
down_revision: Union[str, Sequence[str], None] = '16b2eeb93189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmdb_resources', sa.Column('business_unit', sa.String(length=100), nullable=True, comment='业务线/部门'))
    op.add_column('cmdb_resources', sa.Column('owner', sa.String(length=50), nullable=True, comment='负责人'))
    op.create_index(op.f('ix_cmdb_resources_business_unit'), 'cmdb_resources', ['business_unit'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_owner'), 'cmdb_resources', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmdb_resources_owner'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_business_unit'), table_name='cmdb_resources')
    op.drop_column('cmdb_resources', 'owner')
    op.drop_column('cmdb_resources', 'business_unit')
    # ### end Alembic commands ###
