"""add_resource_detail_fields

Revision ID: 5b1a92a8026b
Revises: 56d86dd10df5
Create Date: 2026-01-26 10:34:11.431747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1a92a8026b'
down_revision: Union[str, Sequence[str], None] = '56d86dd10df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmdb_resources', sa.Column('category', sa.String(length=50), nullable=True, comment='资源分类'))
    op.add_column('cmdb_resources', sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'))
    op.add_column('cmdb_resources', sa.Column('description', sa.String(length=500), nullable=True, comment='描述'))
    op.add_column('cmdb_resources', sa.Column('location', sa.String(length=100), nullable=True, comment='物理位置'))
    op.create_index(op.f('ix_cmdb_resources_category'), 'cmdb_resources', ['category'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_ip_address'), 'cmdb_resources', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmdb_resources_ip_address'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_category'), table_name='cmdb_resources')
    op.drop_column('cmdb_resources', 'location')
    op.drop_column('cmdb_resources', 'description')
    op.drop_column('cmdb_resources', 'ip_address')
    op.drop_column('cmdb_resources', 'category')
    # ### end Alembic commands ###
