"""init_iam_and_cmdb

Revision ID: b68c772f09d0
Revises: 
Create Date: 2026-01-22 16:00:42.101000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68c772f09d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmdb_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmdb_resources_id'), 'cmdb_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_name'), 'cmdb_resources', ['name'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_provider'), 'cmdb_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_region'), 'cmdb_resources', ['region'], unique=False)
    op.create_index(op.f('ix_cmdb_resources_type'), 'cmdb_resources', ['type'], unique=False)
    op.create_table('sys_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_roles_id'), 'sys_roles', ['id'], unique=False)
    op.create_index(op.f('ix_sys_roles_name'), 'sys_roles', ['name'], unique=True)
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=True)
    op.create_index(op.f('ix_sys_users_id'), 'sys_users', ['id'], unique=False)
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_roles_name'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_id'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_cmdb_resources_type'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_region'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_provider'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_name'), table_name='cmdb_resources')
    op.drop_index(op.f('ix_cmdb_resources_id'), table_name='cmdb_resources')
    op.drop_table('cmdb_resources')
    # ### end Alembic commands ###
